language: cpp

#safelist of branches where travis should run
branches:
    only:
        - master    
sudo: true

os:
  - linux

dist: xenial

compiler:
  - clang
  - gcc

env:
  global:
    - PRODUCE_PROOF=OFF
    - USE_READLINE=OFF
  matrix:
    - CMAKE_BUILD_TYPE=Release
    - CMAKE_BUILD_TYPE=Debug

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - env:
      - CMAKE_BUILD_TYPE=Release
      - PRODUCE_PROOF=ON
      compiler: clang
    - env:
      - CMAKE_BUILD_TYPE=Release
      - PRODUCE_PROOF=ON
      compiler: gcc
    - env:
      - CMAKE_BUILD_TYPE=Debug
      - PRODUCE_PROOF=ON
      compiler: gcc


addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgmp-dev
      - libedit-dev
      - bison
      - flex

install: true

before_script:
    - FLAGS="-Wall -Werror"
    - INSTALL=${TRAVIS_BUILD_DIR}/install
    - mkdir build && mkdir ${INSTALL}

script:
  - set -e
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_CXX_FLAGS="$FLAGS" -DPRODUCE_PROOF=${PRODUCE_PROOF} -DUSE_READLINE:BOOL=${USE_READLINE} -DCMAKE_INSTALL_PREFIX=${INSTALL} ..
  - make
  - ctest
  - make install
  - if [[ ${CMAKE_BUILD_TYPE} == Debug && ${PRODUCE_PROOF} == OFF ]]; then
        cd ../regression && ./run-test-notiming.sh ../build/src/bin/opensmt;
    fi
  - if [[ ${CMAKE_BUILD_TYPE} == Debug && ${PRODUCE_PROOF} == ON ]]; then
        cd ../regression_itp && ./run-tests.sh ../build/src/bin/opensmt;
    fi
  - cd ../examples && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DPRODUCE_PROOF=${PRODUCE_PROOF} -DOPENSMT_DIR=${INSTALL} ..
  - make
